kumuluzee:
  name: priporocila-filmi
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/PriporocilaDS
      connection-url: jdbc:postgresql://localhost:5432/priporocila
      username: postgres
      password: postgres
  dev:
    scan-libraries:
      - entitete
      - storitve
integration-properties:
  translate-plus-api:
    host: translate-plus.p.rapidapi.com
    api-key: f21e48fea3msh6904a6d85b24218p14e377jsn8efe83074f6a